[package]
name = "generics_and_zero_sized_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
